build rom cleanup

diff --git a/star-trek-2/Makefile b/star-trek-2/Makefile
--- a/star-trek-2/Makefile
+++ b/star-trek-2/Makefile
@@ -45,9 +45,9 @@ CFLAGS += -I$(ART_BUILD_DIR)/..
 
 # --- Main Targets
 
-all: gamerom
+all: build/gamerom.bin
 
-.PHONY: all art speech clean prereq flash mame roms bootrom
+.PHONY: all art speech clean prereq flash mame roms
 
 prereq:
 	@mkdir -p $(BUILD_DIR)
@@ -61,60 +61,71 @@ clean:
 
 # --- Compilation Targets
 
-gamerom: prereq bootrom speech art
+build/gamerom.bin: build/bootrom.bin $(HDRS) | prereq
 	@echo "building 48k rom 0x0800-0xBFFF, sega-boot-rom in cpu rom socket"
-	zcc +z80 --list -m -vn -SO3 -compiler=sdcc -startup=1 $(SOURCE) -o $@ -create-app $(CFLAGS) -Cz"--rombase=0x0800 --romsize=47104"
-	@mv $@* build/ 2>/dev/null || true
+	zcc +z80 --list -m -vn -SO3 -compiler=sdcc -startup=1 $(SOURCE) -o gamerom -create-app $(CFLAGS) -Cz"--rombase=0x0800 --romsize=47104"
+	@mv gamerom* build/ 2>/dev/null || true
 	@mv *.lis build/ 2>/dev/null || true
-	@printf 'ROM usage: ' && stat -f '%z' build/$@_CODE.bin
-	@printf 'RAM usage: ' && echo "$$(stat -f '%z' build/$@_BSS.bin) + $$(stat -f '%z' build/$@_DATA.bin)" | bc
-	@grep -q "/crt_page_zero_z80.inc:" build/$@.lis || (echo "ERROR crt_page_zero missing. please edit z80_crt_o.asm.m4" && exit 1)
-	@rm -f build/$@.bin
-	cat build/bootrom.bin >> build/$@.bin
-	cat build/$@.rom >> build/$@.bin
-	truncate -s 48K build/$@.bin
+	@printf 'ROM usage: ' && stat -f '%z' build/gamerom_CODE.bin
+	@printf 'RAM usage: ' && echo "$$(stat -f '%z' build/gamerom_BSS.bin) + $$(stat -f '%z' build/gamerom_DATA.bin)" | bc
+	@grep -q "/crt_page_zero_z80.inc:" build/gamerom.lis || (echo "ERROR crt_page_zero missing. please edit z80_crt_o.asm.m4" && exit 1)
+	@rm -f $@
+	cat build/bootrom.bin >> $@
+	cat build/gamerom.rom >> $@
+	truncate -s 48K $@
 
-bootrom: prereq
-	z80asm bootrom.asm -o build/$@.bin
-	truncate -s 2K build/$@.bin
+build/bootrom.bin: bootrom.asm | prereq
+	z80asm bootrom.asm -o $@
+	truncate -s 2K $@
 
 # --- ROM generation
 
-roms: prereq gamerom
+roms: build/gamerom.bin speech | prereq
+	@mkdir -p roms
+	@mkdir -p build/rom
+	@cp ../speech/main.bin roms/1670.speech-u7
+	@truncate -s 2K roms/1670.speech-u7
+	@cp $(SPEECH_BUILD_DIR)/rom_0.bin roms/1871.speech-u6
+	@cp $(SPEECH_BUILD_DIR)/rom_1.bin roms/1872.speech-u5
+	@cp $(SPEECH_BUILD_DIR)/rom_2.bin roms/187x.speech-u4
+	@cp $(SPEECH_BUILD_DIR)/rom_3.bin roms/187x.speech-u3
 	@cp build/bootrom.bin roms/1873.cpu-u25
-	@split -b 2048 build/gamerom.bin roms/part_
-	@i=0; \
-	for f in $$(ls roms/part_* | sort); do \
-		if [ "$$(crc32 "$$f")" = "3f55d17f" ]; then \
-			rm "$$f"; \
-		else \
-			mv "$$f" "roms/$$(($$i + 1847)).prom-u$$i"; \
-		fi; \
-		i=$$(($$i + 1)); \
-	done
-	@rm roms/1847.prom-u0
+	@split -d -b 2048 build/gamerom.bin build/rom/
+	@cp build/rom/01 roms/1848.prom-u1
+	@cp build/rom/02 roms/1849.prom-u2
+	@cp build/rom/03 roms/1850.prom-u3
+	@cp build/rom/04 roms/1851.prom-u4
+	@cp build/rom/05 roms/1852.prom-u5
+	@cp build/rom/06 roms/1853.prom-u6
+	@cp build/rom/07 roms/1854.prom-u7
+	@cp build/rom/08 roms/1855.prom-u8
+	@cp build/rom/09 roms/1856.prom-u9
+	@cp build/rom/10 roms/1857.prom-u10
+	@cp build/rom/11 roms/1858.prom-u11
+	@cp build/rom/12 roms/1859.prom-u12
+	@cp build/rom/13 roms/1860.prom-u13
+	@cp build/rom/14 roms/1861.prom-u14
+	@cp build/rom/15 roms/1862.prom-u15
+	@cp build/rom/16 roms/1863.prom-u16
+	@cp build/rom/17 roms/1864.prom-u17
+	@cp build/rom/18 roms/1865.prom-u18
+	@cp build/rom/19 roms/1866.prom-u19
+	@cp build/rom/20 roms/1867.prom-u20
+	@cp build/rom/21 roms/1868.prom-u21
+	@cp build/rom/22 roms/1869.prom-u22
+	@cp build/rom/23 roms/1870.prom-u23
 
 mame: roms
-	# effectively a patch over the existing to make mame happy
-	$(RM) -rf startrek
-	unzip startrek.zip -d startrek
-	# bring in changes
-	rsync -vt roms/* startrek 
-	# new speech data
-	cp $(SPEECH_BUILD_DIR)/rom_0.bin startrek/1871.speech-u6
-	cp $(SPEECH_BUILD_DIR)/rom_1.bin startrek/1872.speech-u5
-	cp $(SPEECH_BUILD_DIR)/rom_2.bin startrek/187x.speech-u4
-	cp $(SPEECH_BUILD_DIR)/rom_3.bin startrek/187x.speech-u3
-	# new 8035 speech mcu driver
-	cp ../speech/main.bin startrek/1670.speech-u7
-	zip roms.zip startrek/*
-	$(RM) -rf startrek
-	mv roms.zip build/startrek.zip
-	$(MAME) -rp ./build startrek
+	# mame needs a couple phony proms too
+	@truncate -s 32 roms/6331.speech-u30
+	@truncate -s 32 roms/pr-82.cpu-u15
+	cp ./s-c.xyt-u39 roms/
+	zip -qj roms/startrek.zip roms/* -x "*.zip"
+	$(MAME) -rp ./roms startrek
 
 # --- art 
 
-art: prereq $(HDRS)
+art: $(HDRS) | prereq
 
 $(ART_BUILD_DIR)/logo%.h: art/logo%.svg
 	../tools/svg2sega.py --scale 2.0 --rotate 90 --speed 0 --origin-left --merge 1.0 --rdp 0 --no-opt --close $< > $@
@@ -133,7 +144,7 @@ $(ART_BUILD_DIR)/%.h: art/font/%.svg
 
 # --- speech 
 
-speech: prereq $(LPC_TARGETS)
+speech: $(LPC_TARGETS) | prereq
 	@echo "Packing LPC files into 4K chunks..."
 	python3 ../tools/pack_lpc.py $(SPEECH_BUILD_DIR) $(SPEECH_BUILD_DIR)/rom
 
